name: CI/CD
run-name: ${{ github.action }} lint and type-check triggered on ${{ github.event_name }} by ${{ github.actor }}
on: [push, pull_request]
jobs:
  locate-us:
    runs-on: ubuntu-latest
    steps:
      - run: ls
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "linting project with ESLint."
      - run: npm run lint-fix
  type-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "type-checking project with tsc."
      - run: npm run ts-test
