# name: CI/CD
# run-name: ${{ github.action }} lint and type-check triggered on ${{ github.event_name }} by ${{ github.actor }}
# on: [push, pull_request]
# jobs:
#   identify:
#     runs-on: ubuntu-latest
#     steps:
#       - run: ls
#   lint-and-fix:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "linting project with ESLint."
#       - run: npm run lint-fix
#         working-directory: ${{ github.workspace }}
#   type-check:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "type-checking project with tsc."
#       - run: npm run ts-test
#         working-directory: ${{ github.workspace }}
name: List files example

on: [push]

jobs:
  explore-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -la # Use -la for long format including hidden files
        
      - name: Check out repository code
        uses: actions/checkout@v4 # It's best practice to use the checkout action

      - name: List files after checkout
        run: |
          echo "Listing files in the workspace directory:"
          ls -la ${{ github.workspace }} # Use the github.workspace context
